#!/bin/bash

# user settings
LOG_FILE="/var/log/letsencrypt/renew.log"
RENEW_CMD="/etc/letsencrypt/certbot-auto renew"
MSG_FAIL="RENEWAL FAILURE"
MSG_SUCCESS="RENEWAL SUCCESS"

CUR_TIME=$(date)

# certbot needs control of :80, so stop apache
service apache2 stop

# send both stderr & stdout to logfile
# this is important b/c sometimes there's useful debug info
# in stdout during errors
$RENEW_CMD &>> $LOG_FILE
RENEW_STATUS=$?

service apache2 start

# even though it's already logging verbosely,
# make it easier to grep for the outcome
# TODO: consider two logs: one simple, one verbose?
if [ "$RENEW_STATUS" != 0 ]; then
        echo "$MSG_FAIL $CUR_TIME" >> $LOG_FILE
else
        echo "$MSG_SUCCESS $CUR_TIME" >> $LOG_FILE
fi

exit $RENEW_STATUS
