#!/bin/bash

CUR_TIME=$(date)

# TODO: move to cl arg
LOG_FILE="/var/log/letsencrypt/renew.log"
RENEW_CMD="/etc/letsencrypt/certbot-auto renew"

FAIL_MSG="RENEWAL FAILURE"
SUCCESS_MSG="RENEWAL SUCCESS"

# certbot needs control of :80, so stop apache
service apache2 stop

# send both stderr & stdout to logfile
# this is important b/c sometimes there's useful info
# in stdout during errors
$RENEW_CMD &>> $LOG_FILE
BOT_STATUS=$?

service apache2 start

# even though it's logging verbosely above,
# make it easy to grep the basics
# TODO: consider two logs: one simple, one verbose?
if [ "$BOT_STATUS" != 0 ]; then
        echo "$FAIL_MSG $CUR_TIME" >> $LOG_FILE
        exit $BOT_STATUS
else
        echo "$SUCCESS_MSG $CUR_TIME" >> $LOG_FILE
        exit $BOT_STATUS
fi
